---

- name: check_hadoop_group_exists
  shell: grep -e "^hadoop" /etc/group
  register: check_hadoop_group

- name: add_spark_user_in_hadoop_group
  user: name=spark groups=hadoop
  when: check_hadoop_group.rc == 0

- name: add_spark_user
  user: name=spark
  when: check_hadoop_group.rc != 0


- name: install_spark_history_server
  yum: name=spark-history-server state=installed

- name: start_spark-history-server
  service: name=spark-history-server state=started