---
# file: roles/cdh_hbase_regionserver/tasks/main.yml

- name: configure rsyslog for hbase-regionserver
  template: src=rsyslog.conf dest=/etc/rsyslog.d/60-hbase-regionserver.conf owner=root group=root mode=0644
  tags: rsyslog
  notify:
    - restart rsyslog

- name: install hbase-regionserver 
  yum: name=hbase-regionserver state=latest
  tags: hbase
  notify:
    - start hbase-regionserver