---
# file: roles/apache2/tasks/main.yml

- name: install apache2 
  yum: name={{ item }} state=latest
  with_items:
     - httpd
  tags: apache

- name: configure httpd so it doesn't complain 'can't determine fqdn'
  lineinfile: dest=/etc/httpd/httpd.conf regexp="{{ ansible_fqdn }}" line="ServerName {{ ansible_fqdn }}"
  notify:
    - reload apache config
  tags: apache
