---
# file: roles/elasticsearch_curator/tasks/main.yml

- name: install elasticsearch-curator 
  yum: name=elasticsearch-curator state=latest
  tags: elasticsearch_curator

- name: install the elasticsearch-curator crontab at /etc/cron.d/elasticsearch-curator
  template: src=elasticsearch-curator.cron.d dest=/etc/cron.d/elasticsearch-curator owner=root group=root mode=644
  tags: elasticsearch_curator