---

- name: install_gmetad
  yum: name={{ item }} state=installed
  with_items:
    - ganglia-gmetad
    - ganglia-web

- name: copy_gmetad.conf
  template: src=gmetad.conf.j2 dest=/etc/ganglia/gmetad.conf
  notify:
    - restart_gmetad

- name: copy_ganglia.conf
  template: src=ganglia.conf.j2 dest=/etc/httpd/conf.d/ganglia.conf
  notify:
    - restart_gmetad


- name: start_gmetad_on_boot
  service: name=gmetad state=started enabled=yes
