---
- hosts: vm-host

  tasks:
    - name: destroy vm
      virt: command=destroy name={{ vm_name }} uri=qemu:///system
      ignore_errors: yes

    - name: undefine vm
      virt: command=undefine name={{ vm_name }} uri=qemu:///system
      ignore_errors: yes

    - name: remove vm root logical volume
      lvol: vg={{ vm_volume_group }} lv={{ vm_name }} state=absent force=yes

    - name: recovery sriov file
      shell: mv /tmp/sriov/use/{{ vm_name }}  /tmp/sriov/unuse/{{ vm_name }}
      when: "net_type == 'sriov'"

