---
- name: make_group_storm
  group: name=storm
  tags: storm

- name: make_user_storm
  user: name=storm group=storm
  tags: storm

- name: install storm
  yum: name={{ item }} state=latest
  with_items:
    - storm
    - storm-supervisor
    - storm-ui
    - storm-drpc
    - storm-nimbus
  tags: storm
