---
- name: create vm root logical volume
  lvol: lv={{ vm_name }} vg={{ vm_volume_group }} size={{ vm_root_volume_size }} state=present

- name: create vm filesystem
  filesystem: fstype=xfs dev=/dev/{{ vm_volume_group }}/{{ vm_name }}

- name: find vm root device UUID
  command: blkid -o value -s UUID /dev/{{ vm_volume_group }}/{{ vm_name }}
  register: root_device_uuid_discovery

- name: register vm root device UUID
  set_fact: vm_root_device_uuid={{ root_device_uuid_discovery.stdout }}
