---
# file: roles/presto_coordinator/tasks/main.yml

- name: configure presto coordinator
  template: src={{ item }} dest=/etc/presto/{{ item }} owner=root group=root mode=0644
  with_items:
    - config.properties
  notify:
    - restart presto
  tags:
    - configuration
    - presto